"""
NFS 共享模块
"""
import os
import subprocess
import re
from dataclasses import dataclass, asdict
from typing import List, Optional, Dict


@dataclass
class NFSShare:
    """NFS 共享配置"""
    path: str
    clients: str = "*"  # 可以访问的客户端
    options: str = "rw,sync,no_subtree_check,no_root_squash"
    comment: str = ""
    
    # 常用选项
    READ_ONLY = "ro,sync,no_subtree_check"
    READ_WRITE = "rw,sync,no_subtree_check,no_root_squash"
    READ_ONLY_ROOT = "ro,sync,no_subtree_check,root_squash"
    
    def to_export_line(self) -> str:
        """转换为 exports 格式"""
        options = self.options or "rw,sync,no_subtree_check"
        comment = f" # {self.comment}" if self.comment else ""
        return f"{self.path} {self.clients}({options}){comment}"
    
    @classmethod
    def from_export_line(cls, line: str) -> Optional['NFSShare']:
        """从 exports 行解析"""
        line = line.strip()
        if not line or line.startswith('#'):
            return None
        
        # 解析: /path client1(options) # comment
        match = re.match(r'(\S+)\s+(\S+)\(([^)]+)\)(?:\s+#\s*(.*))?', line)
        if match:
            return cls(
                path=match.group(1),
                clients=match.group(2),
                options=match.group(3),
                comment=match.group(4) or ""
            )
        return None


class NFSManager:
    """NFS 共享管理器"""
    
    def __init__(self, exports_file: str = "/etc/exports"):
        self.exports_file = exports_file
        self.shares: Dict[str, NFSShare] = {}
        self._load_exports()
    
    def _run_cmd(self, cmd: List[str]) -> str:
        """执行命令"""
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=10)
        if result.returncode != 0:
            raise RuntimeError(f"Command failed: {result.stderr}")
        return result.stdout
    
    def _load_exports(self):
        """加载现有 exports 配置"""
        if not os.path.exists(self.exports_file):
            return
        
        with open(self.exports_file, 'r') as f:
            for line in f:
                share = NFSShare.from_export_line(line)
                if share:
                    self.shares[share.path] = share
    
    def list_shares(self) -> List[NFSShare]:
        """列出所有 NFS 共享"""
        return list(self.shares.values())
    
    def get_share(self, path: str) -> Optional[NFSShare]:
        """获取共享配置"""
        return self.shares.get(path)
    
    def create_share(self, share: NFSShare) -> Dict:
        """创建 NFS 共享"""
        # 检查路径
        if not os.path.exists(share.path):
            try:
                os.makedirs(share.path, exist_ok=True)
            except OSError as e:
                return {"status": "error", "message": f"Cannot create path: {e}"}
        
        # 检查权限
        if not os.access(share.path, os.R_OK):
            try:
                os.chmod(share.path, 0o755)
            except OSError:
                pass
        
        self.shares[share.path] = share
        
        if self._write_exports():
            self._reload_nfs()
            return {"status": "success", "share": asdict(share)}
        
        return {"status": "error", "message": "Failed to write exports"}
    
    def update_share(self, path: str, updates: Dict) -> Dict:
        """更新共享配置"""
        if path not in self.shares:
            return {"status": "error", "message": "Share not found"}
        
        share = self.shares[path]
        for k, v in updates.items():
            if hasattr(share, k):
                setattr(share, k, v)
        
        if self._write_exports():
            self._reload_nfs()
            return {"status": "success", "share": asdict(share)}
        
        return {"status": "error", "message": "Failed to update"}
    
    def delete_share(self, path: str) -> Dict:
        """删除共享"""
        if path not in self.shares:
            return {"status": "error", "message": "Share not found"}
        
        del self.shares[path]
        
        if self._write_exports():
            self._reload_nfs()
            return {"status": "success", "path": path}
        
        return {"status": "error", "message": "Failed to delete"}
    
    def _write_exports(self) -> bool:
        """写入 exports 配置"""
        try:
            lines = [
                "# /etc/exports - NFS share config",
                "# Generated by NAS System",
                "",
            ]
            
            for share in self.shares.values():
                lines.append(share.to_export_line())
            
            with open(self.exports_file, 'w') as f:
                f.write('\n'.join(lines) + '\n')
            
            return True
        except Exception as e:
            print(f"Error writing exports: {e}")
            return False
    
    def _reload_nfs(self):
        """重新加载 NFS 配置"""
        try:
            # 导出所有共享
            subprocess.run(["exportfs", "-ra"], capture_output=True, timeout=10)
        except Exception as e:
            print(f"Error reloading NFS: {e}")
    
    def get_connected_clients(self) -> List[Dict]:
        """获取已连接的 NFS 客户端"""
        clients = []
        try:
            output = self._run_cmd(["showmount", "-a"])
            
            for line in output.split('\n'):
                if ':' in line:
                    parts = line.split(':')
                    if len(parts) >= 2:
                        clients.append({
                            "client": parts[0].strip(),
                            "path": parts[1].strip()
                        })
        except:
            pass
        
        return clients
    
    def get_exported_paths(self) -> List[str]:
        """获取已导出的路径"""
        paths = []
        try:
            output = self._run_cmd(["exportfs", "-v"])
            
            for line in output.split('\n'):
                if '/' in line:
                    match = re.search(r'(\S+)', line)
                    if match:
                        path = match.group(1)
                        if path.startswith('/'):
                            paths.append(path)
        except:
            pass
        
        return paths
    
    def get_status(self) -> Dict:
        """获取 NFS 服务状态"""
        try:
            # 检查 rpcbind
            subprocess.run(["rpcinfo", "-p"], capture_output=True, timeout=5)
            
            # 检查 nfsd
            result = subprocess.run(
                ["systemctl", "is-active", "nfs-server"],
                capture_output=True, text=True, timeout=5
            )
            nfs_active = result.stdout.strip() == "active"
            
            return {
                "status": "running" if nfs_active else "stopped",
                "rpcbind": "ok",
                "nfsd": "ok" if nfs_active else "not running"
            }
        except FileNotFoundError:
            return {"status": "not_installed"}
        except Exception as e:
            return {"status": "error", "message": str(e)}
    
    def start_service(self) -> Dict:
        """启动 NFS 服务"""
        try:
            subprocess.run(["systemctl", "start", "nfs-server"], 
                         capture_output=True, timeout=10)
            return {"status": "success"}
        except Exception as e:
            return {"status": "error", "message": str(e)}
    
    def stop_service(self) -> Dict:
        """停止 NFS 服务"""
        try:
            subprocess.run(["systemctl", "stop", "nfs-server"], 
                         capture_output=True, timeout=10)
            return {"status": "success"}
        except Exception as e:
            return {"status": "error", "message": str(e)}


# 全局 NFS 管理器
nfs_manager = NFSManager()